<a href="https://colab.research.google.com/github/Abhigyan76/Cerina-Healthcare-assignment/blob/main/Basic%20to%20NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
class Category:
  BOOKS ="BOOKS"
  CLOTHING= "CLOTHING"


train_x = ["I love teh book","this is a great book","the fit is great","I love the shoes"]
train_y = [Category.BOOKS,Category.BOOKS,Category.CLOTHING,Category.CLOTHING]

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
vectorizer = CountVectorizer(binary = True, ngram_range=(1,2))
vectors = vectorizer.fit_transform(train_x)

In [ ]:
print(vectors[0])

  (0, 7)	1
  (0, 11)	1
  (0, 0)	1
  (0, 8)	1
  (0, 12)	1


In [ ]:
print(vectorizer.get_feature_names_out())

['book' 'fit' 'fit is' 'great' 'great book' 'is' 'is great' 'love'
 'love teh' 'love the' 'shoes' 'teh' 'teh book' 'the' 'the fit'
 'the shoes' 'this' 'this is']


In [ ]:
print(vectors.toarray())

[[1 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0]
 [1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1]
 [0 1 1 1 0 1 1 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 1 0 0]]


In [ ]:
from sklearn import svm

In [ ]:
train_x_vectors = vectorizer.fit_transform(train_x)

In [ ]:
clf_svm = svm.SVC(kernel='linear')

In [ ]:
clf_svm.fit(train_x_vectors, train_y)

SVC(kernel='linear')

In [ ]:
test_x = vectorizer.transform(['I like the book'])


In [ ]:
clf_svm.predict(test_x)

array(['CLOTHING'], dtype='<U8')

## Word Vectors

In [ ]:
!pip install spacy

Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> 
KeyboardInterrupt
>>> ^C


In [ ]:
!python -m spacy download en_core_web_md


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.8/42.8 MB 11.0 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
import spacy

In [ ]:
nlp = spacy.load("en_core_web_md")

In [ ]:
print(train_x)

['I love teh book', 'this is a great book', 'the fit is great', 'I love the shoes']


In [ ]:
docs = [nlp(text) for text in train_x]
print(docs)

[I love teh book, this is a great book, the fit is great, I love the shoes]


In [ ]:
docs = [nlp(text) for text in train_x]
train_x_word_vectors = [x.vector for x in docs]

In [ ]:
print(docs[0].vector)

[-7.67147481e-01  1.62885070e-01 -1.58080018e+00 -5.89874983e+00
 -5.93773031e+00 -9.28225040e-01  1.80184984e+00  2.70082498e+00
 -5.41692495e+00  3.62705493e+00  3.29920030e+00  1.60275006e+00
 -6.15175533e+00  6.21495068e-01  2.94847488e+00 -4.55737495e+00
  3.59426498e+00 -3.27339983e+00 -9.55049932e-01  9.33449984e-01
  2.30620265e+00  2.75677514e+00 -3.54054999e+00 -5.81167221e+00
 -1.26215005e+00 -4.32699776e+00 -8.70525002e-01  1.98154998e+00
 -8.73924911e-01  2.33857250e+00 -2.18000007e+00 -1.66687489e+00
 -6.92200005e-01  3.81832504e+00  4.92584801e+00  1.08302248e+00
 -2.46169996e+00 -1.24536252e+00  3.01119995e+00 -1.20280802e+00
 -1.42805004e+00  3.20234990e+00  1.33826506e+00 -2.01500010e+00
  5.47327518e+00  3.31602502e+00 -3.52597499e+00 -3.91094756e+00
  3.31967473e-01  2.47609997e+00 -7.38474965e-01 -4.16055012e+00
  5.93660057e-01 -2.02436018e+00 -5.40198803e+00 -2.68182456e-01
  9.80307460e-01  1.23725331e+00  4.55058289e+00  2.83588743e+00
  7.39575052e+00 -1.41459

In [ ]:
clf_svm_wv = svm.SVC(kernel='linear')
clf_svm_wv.fit(train_x_word_vectors, train_y)

SVC(kernel='linear')

In [ ]:
test_x = ["I love the book"]
test_docs = [nlp(text) for text in test_x]
test_x_word_vectors = [x.vector for x in test_docs]
clf_svm_wv.predict(test_x_word_vectors)

array(['CLOTHING'], dtype='<U8')

## Regexes

In [ ]:
import re

In [ ]:
regexp = re.compile(r"^ab[^\s]*cd$")

phrases = ["abcd","xxx","abxxxcd","ab cd"]
matches = []
for phrase in phrases:
  if re.match(regexp, phrase):
    matches.append(phrase)

print(matches)


['abcd', 'abxxxcd']


## Stemming/Lemmetization

In [ ]:
 import nltk

In [ ]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer

In [ ]:
stemmer = PorterStemmer()
phrase = "reading the books"
words = word_tokenize(phrase)

stemmed_words = []
for word in words:
  stemmed_words.append(stemmer.stem(word))

"".join(stemmed_words)

'readthebook'

In [ ]:
from nltk.stem import WordNetLemmatizer

In [ ]:
lemmatizer = WordNetLemmatizer()

In [ ]:
phrase = "reading the books"
words = word_tokenize(phrase)


lemmatized_words = []
for word in words:
  lemmatized_words.append(lemmatizer.lemmatize(word))

In [ ]:
"".join(lemmatized_words)

'readingthebook'

## Stopword Removal

In [ ]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [ ]:
stop_words = stopwords.words('english')

In [ ]:
print(stop_words)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [ ]:
phrase ="Here is an example esentence demonstrating the removal of stopwords"
words = word_tokenize(phrase)

stripped_phrase = []
for word in words:
  if words not in stop_words:
    stripped_phrase.append(word)
"".join (stripped_phrase)

'Hereisanexampleesentencedemonstratingtheremovalofstopwords'

## Various other methods

In [ ]:
from textblob import TextBlob

In [ ]:
phrase = "Tthhis is an example"
tb_phrase = TextBlob(phrase)
tb_phrase.correct()

TextBlob("This is an example")

In [ ]:
!python -m textblob.download_corpora

[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Unzipping corpora/conll2000.zip.
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Unzipping corpora/movie_reviews.zip.
Finished.


In [ ]:
tb_phrase.tags

[('Tthhis', 'NNP'), ('is', 'VBZ'), ('an', 'DT'), ('example', 'NN')]

In [ ]:
tb_phrase.sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

## Transformer Architecture

In [ ]:
! pip install spacy.transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 197.8/197.8 kB 3.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 14.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 314.0/314.0 kB 20.8 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manyli

In [ ]:
pip install spacy spacy-transformers


In [ ]:
!python -m spacy download en_core_web_trf


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.4/457.4 MB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.3/236.3 kB 4.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.6/731.6 kB 30.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [ ]:
# !python -m spacy download en_trf_bertbaseuncased_lg

In [ ]:
import spacy
import torch

In [ ]:
nlp = spacy.load("en_trf_bertbaseuncased_lg")

OSError: [E050] Can't find model 'en_trf_bertbaseuncased_lg'. It doesn't seem to be a Python package or a valid path to a data directory.

In [ ]:
doc = nlp("here is some text to encode")

In [ ]:
class Category:
  BOOKS ="BOOKS"
  BANK= "BANK"


train_x = ["good characters and plot progression","check out the book","good story,would recommend","novel recommendation","need recommendation","need to make a depostion"]
train_y = [Category.BOOKS,Category.BOOKS, Category.BANK,Category.BANK,Category.BANK]

In [ ]:
from sklearn import svm

In [ ]:
docs = [nlp(text) for text in train_x]
train_x_vectors = [doc.vector for doc in docs]
clf_svm = svm.SVC(kernel= 'linear')

In [ ]:
clf_svm.fit(train_x_vectors,train_y)

ValueError: Found input variables with inconsistent numbers of samples: [6, 5]

In [ ]:
test_x=["I need to write a check"]
docs = [nlp(text)for text in test_x]
test_x_vectors = [doc.vector for doc in docs]

In [ ]:
clf_svm.predict(test_x_vectors)

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.